### ISSUE TITLE
[Backend] Organization able to register and update detail for their devices.

### ISSUE THREAD

**Issue by truonghoangduy** [GDSC-HSU/gateway#12]
### EPIC : 
Dependency : #11 when user already has the organization endpoint 
The functionality is allow organization to add the device(mobile) and configure device information into their 
organization for device management.

**System actor** : Mobile, Web

### Description : 

Organization on their Web dashboard and create new device (without any information), only has the QRCode encoded with the device-assess-key, **When Mobile scan the QRCode** so that it could claim(device-assess-key) the created device and upload it information to the organization. 

New device are created with the organization with the following information [x]. When device are added susses-fully organization are able to modify their  **changeable information**

This bellow information will be saved to the mobile app (local data) and use for device authentication.

 **[x] device information**
 
 ```yml
Device name: string -changeable

Device location: string 
(Name of streets, school campus location or custom markup, GPS stamp) -changeable

Device unique id: string 
 (user for api parameter)
 
Device assess key: string

Device MAC address: string

Tag: array of string
(Device tag for query, filter purpose) -changeable
```

**Device authentication** only use device-assess-key , device-id, device-mac
Hardware information data : MAC address

---

**Specification** 
- [ ] Endpoint for create device, response with the device-id, device-access-key and blank information
- [ ] Endpoint for update changeable information with the already registered device.
- [ ] Endpoint for Mobile to claim and upload it hardware information data to the created device, respond back the device information.
- [ ] Test endpoint by getting device information by device-id

**How device claim work**
1. Device scan the QR encoded with device-assess-key
1. Device claim the new created in the backend by provide scanned device-assess-key
1. When claim device upload it hardware data to claim the created device

**Note**

- Fill free to contact for model change, un-clear requirements/explanation
