### ISSUE TITLE
Device are able to"POST" their sensor data

### ISSUE THREAD

**Issue by truonghoangduy** [GDSC-HSU/gateway#13]
### EPIC:

The functionality allow device (mobile) to transfer their data into organization backend. Later they could gather the data or make query or filter on it.

### Description:

The device (mobile) app after each person interact their data [x] will be transfer to organization backend.

Header: device access token

[x]

```yml
body_temperature : float
face_mask: bool
covid_identification: 
        identification_method: QR | RFID
        identification_data : string
is_complete : bool (indicate weather user completing all the step, or they just do covid_identification)
Timestamp:
```

**Note**:
- **Timestamp** using server time

**Specification**

- [ ] End point for device to post their data.

**Note**

- Fill free to contact for model change, un-clear requirements/explanation
