### ISSUE TITLE
[DOCS] [Backend] User able to create their organization

### ISSUE THREAD

**Issue by truonghoangduy** [GDSC-HSU/gateway#20]
### EPIC : 
User able to create their organization, and following on using the rest of the backend api belong to their created organization

### Description : 
Web client after they log in with email, password. If they are not participating in an organization they have an option to create an organization.

When an organization is created successfully, they will be able to use their organization endpoint 

"https://{our_project_domain}/org/{organization_id}/"

 ```yml
organization_name: "Google Developer Student Clubs of Hoa Sen university"
organization_img: "xxx-xxxx-xxxx.jpeg"
organization_endpoint : "https://{our_project_domain}/org/{organization_id}/"
organization_id: "gdsc-hsu"
```
*Note: 

- **organization_id is uquie** (frist-come-frist-serve)
- organization_name: could be duplicated

---

**Specification** 
- [ ] Bullet end point

**Note**

- Fill free to contact for model change, un-clear requirements/explanation
